# Generated by Django 5.1.4 on 2024-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Age',
            field=models.IntegerField(max_length=3),
        ),
    ]
